// Code generated by ormc; DO NOT EDIT.
// NOTE: Schema() and Values() must always be in the same field order.
// String PK: set via github.com/tinywasm/unixid before calling db.Create().
package businesshours

import (
	"github.com/tinywasm/orm"
)

func (m *BusinessHours) Schema() []orm.Field {
	return []orm.Field{
		{Name: "id", Type: orm.TypeText, Constraints: orm.ConstraintPK},
		{Name: "day_of_week", Type: orm.TypeInt64, Constraints: orm.ConstraintUnique | orm.ConstraintNotNull},
		{Name: "open_time", Type: orm.TypeText, Constraints: orm.ConstraintNotNull},
		{Name: "close_time", Type: orm.TypeText, Constraints: orm.ConstraintNotNull},
		{Name: "is_open", Type: orm.TypeBool, Constraints: orm.ConstraintNotNull},
		{Name: "notes", Type: orm.TypeText, Constraints: orm.ConstraintNone},
		{Name: "updated_at", Type: orm.TypeInt64, Constraints: orm.ConstraintNotNull},
	}
}

func (m *BusinessHours) Values() []any {
	return []any{
		m.ID,
		m.DayOfWeek,
		m.OpenTime,
		m.CloseTime,
		m.IsOpen,
		m.Notes,
		m.UpdatedAt,
	}
}

func (m *BusinessHours) Pointers() []any {
	return []any{
		&m.ID,
		&m.DayOfWeek,
		&m.OpenTime,
		&m.CloseTime,
		&m.IsOpen,
		&m.Notes,
		&m.UpdatedAt,
	}
}

var BusinessHoursMeta = struct {
	TableName string
	ID string
	DayOfWeek string
	OpenTime string
	CloseTime string
	IsOpen string
	Notes string
	UpdatedAt string
}{
	TableName: "business_hours",
	ID: "id",
	DayOfWeek: "day_of_week",
	OpenTime: "open_time",
	CloseTime: "close_time",
	IsOpen: "is_open",
	Notes: "notes",
	UpdatedAt: "updated_at",
}

func ReadOneBusinessHours(qb *orm.QB, model *BusinessHours) (*BusinessHours, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllBusinessHours(qb *orm.QB) ([]*BusinessHours, error) {
	var results []*BusinessHours
	err := qb.ReadAll(
		func() orm.Model { return &BusinessHours{} },
		func(m orm.Model) { results = append(results, m.(*BusinessHours)) },
	)
	return results, err
}
