// DO NOT EDIT. generated by github.com/tinywasm/ormc

package businesshours

import (
	"github.com/tinywasm/model"
	"github.com/tinywasm/orm"
)

type BusinessHours struct {
	Id string
	DayOfWeek int64
	OpenTime string
	CloseTime string
	IsOpen bool
	Notes string
	UpdatedAt int64
}

func (m *BusinessHours) ModelName() string { return "business_hours" }

func (m *BusinessHours) Schema() []model.Field { return BusinessHoursModel.Fields }

func (m *BusinessHours) Pointers() []any { return []any{&m.Id, &m.DayOfWeek, &m.OpenTime, &m.CloseTime, &m.IsOpen, &m.Notes, &m.UpdatedAt} }

func (m *BusinessHours) IsNil() bool { return m == nil }

func (m *BusinessHours) EncodeFields(w model.FieldWriter) {
	w.String("id", m.Id)
	w.Int("day_of_week", m.DayOfWeek)
	w.String("open_time", m.OpenTime)
	w.String("close_time", m.CloseTime)
	w.Bool("is_open", m.IsOpen)
	w.String("notes", m.Notes)
	w.Int("updated_at", m.UpdatedAt)
}

func (m *BusinessHours) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok { m.Id = v }
	if v, ok := r.Int("day_of_week"); ok { m.DayOfWeek = v }
	if v, ok := r.String("open_time"); ok { m.OpenTime = v }
	if v, ok := r.String("close_time"); ok { m.CloseTime = v }
	if v, ok := r.Bool("is_open"); ok { m.IsOpen = v }
	if v, ok := r.String("notes"); ok { m.Notes = v }
	if v, ok := r.Int("updated_at"); ok { m.UpdatedAt = v }
}

type BusinessHoursList []*BusinessHours

func (s *BusinessHoursList) Schema() []model.Field { return nil }
func (s *BusinessHoursList) Pointers() []any     { return nil }
func (s *BusinessHoursList) Len() int             { return len(*s) }
func (s *BusinessHoursList) At(i int) model.Fielder { return (*s)[i] }
func (s *BusinessHoursList) Append() model.Fielder  { v := &BusinessHours{}; *s = append(*s, v); return v }
func (s *BusinessHoursList) IsNil() bool          { return s == nil }
func (s *BusinessHoursList) EncodeFields(_ model.FieldWriter) {}
func (s *BusinessHoursList) DecodeFields(_ model.FieldReader) {}

func (m *BusinessHours) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var BusinessHours_ = struct {
	Id string
	DayOfWeek string
	OpenTime string
	CloseTime string
	IsOpen string
	Notes string
	UpdatedAt string
}{
	Id: "id",
	DayOfWeek: "day_of_week",
	OpenTime: "open_time",
	CloseTime: "close_time",
	IsOpen: "is_open",
	Notes: "notes",
	UpdatedAt: "updated_at",
}

func ReadOneBusinessHours(qb *orm.QB, model *BusinessHours) (*BusinessHours, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllBusinessHours(qb *orm.QB) (BusinessHoursList, error) {
	var results BusinessHoursList
	err := qb.ReadAll(
		func() model.Model { return &BusinessHours{} },
		func(m model.Model) { results = append(results, m.(*BusinessHours)) },
	)
	return results, err
}

