// DO NOT EDIT. generated by github.com/tinywasm/orm

package businesshours

import (
	"github.com/tinywasm/fmt"
	"github.com/tinywasm/orm"
)

func (m *BusinessHours) ModelName() string {
	return "business_hours"
}

var _schemaBusinessHours = []fmt.Field{
		{Name: "id", Type: fmt.FieldText, DB: &fmt.FieldDB{PK: true}},
		{Name: "day_of_week", Type: fmt.FieldInt, DB: &fmt.FieldDB{Unique: true}, NotNull: true},
		{Name: "open_time", Type: fmt.FieldText, NotNull: true},
		{Name: "close_time", Type: fmt.FieldText, NotNull: true},
		{Name: "is_open", Type: fmt.FieldBool, NotNull: true},
		{Name: "notes", Type: fmt.FieldText},
		{Name: "updated_at", Type: fmt.FieldInt, NotNull: true},
	}

func (m *BusinessHours) Schema() []fmt.Field { return _schemaBusinessHours }

func (m *BusinessHours) Pointers() []any {
	return []any{
		&m.ID,
		&m.DayOfWeek,
		&m.OpenTime,
		&m.CloseTime,
		&m.IsOpen,
		&m.Notes,
		&m.UpdatedAt,
	}
}

func (m *BusinessHours) Validate(action byte) error {
	return fmt.ValidateFields(action, m)
}

var BusinessHours_ = struct {
	ModelName string
	ID string
	DayOfWeek string
	OpenTime string
	CloseTime string
	IsOpen string
	Notes string
	UpdatedAt string
}{
	ModelName: "business_hours",
	ID: "id",
	DayOfWeek: "day_of_week",
	OpenTime: "open_time",
	CloseTime: "close_time",
	IsOpen: "is_open",
	Notes: "notes",
	UpdatedAt: "updated_at",
}

func ReadOneBusinessHours(qb *orm.QB, model *BusinessHours) (*BusinessHours, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllBusinessHours(qb *orm.QB) ([]*BusinessHours, error) {
	var results []*BusinessHours
	err := qb.ReadAll(
		func() fmt.Model { return &BusinessHours{} },
		func(m fmt.Model) { results = append(results, m.(*BusinessHours)) },
	)
	return results, err
}

